services:
  # БД для stat сервиса
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"

  # stat сервис
  stats-server:
    build:
      context: .
      dockerfile: stat/Dockerfile
    depends_on: [stats-db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    ports:
      - "9090:9090"

  # БД для main сервиса
  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "6543:5432"

  # main сервис
  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    depends_on: [ewm-db, stats-server]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: main
      SPRING_DATASOURCE_PASSWORD: main
      STAT_SVC_URL: http://stats-server:9090
    ports:
      - "8080:8080"
