services:
  # БД для stat сервиса
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"

  # БД для main сервиса
  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "5432:5432"
