services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  request-db:
    image: postgres:16.1
    container_name: postgres-ewm-request-db
    environment:
      POSTGRES_DB: ewm_request
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request
    ports:
      - 5434:5432
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  user-db:
    image: postgres:16.1
    container_name: postgres-ewm-user-db
    environment:
      POSTGRES_DB: ewm_user
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5435:5432
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15
#
#  discovery-server:
#    build: infra/discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    networks:
#      - ewm-net
#    healthcheck:
#      test: "curl --fail --silent discovery-server:8761/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 20s
#      retries: 5
#
#  config-server:
#    build: infra/config-server
#    container_name: config-server
#    networks:
#      - ewm-net
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=9091
#    healthcheck:
#      test: "curl --fail --silent config-server:9091/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 30s
#      retries: 5
#
#  gateway-server:
#    build: infra/gateway-server
#    container_name: gateway-server
#    ports:
#      - "8080:8080"
#    networks:
#      - ewm-net
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#
#  user-service:
#    build: core/user-service
#    container_name: ewm-user-service
#    networks:
#      - ewm-net
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/ewm_user
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=8084
#    healthcheck:
#      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 25s
#      retries: 10
#
#  request-service:
#    build: core/request-service
#    container_name: ewm-request-service
#    networks:
#      - ewm-net
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/ewm_request
#      - SPRING_DATASOURCE_USERNAME=request
#      - SPRING_DATASOURCE_PASSWORD=request
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=8083
#    healthcheck:
#      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 25s
#      retries: 10
#
#  main-service:
#    build: core/main-service
#    container_name: main-service
#    networks:
#      - ewm-net
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#      - SERVER_PORT=8081
#    healthcheck:
#      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 25s
#      retries: 10
#
#  stats-server:
#    build: stats/stats-server
#    container_name: ewm-stats-server
#    ports:
#      - "9090:9090"
#    networks:
#      - ewm-net
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
#      - SPRING_DATASOURCE_USERNAME=stats
#      - SPRING_DATASOURCE_PASSWORD=stats
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    healthcheck:
#      test: "curl --fail --silent localhost:9090/actuator/health | grep UP || exit 1"
#      timeout: 5s
#      interval: 15s
#      retries: 10




networks:
  ewm-net:
